"use client";
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import '/public/styles.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Find a Family Doctor',
  description: 'Generated by create next app',
};

const queryClient = new QueryClient();

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <Providers>{children}</Providers>
        </QueryClientProvider>
      </body>
    </html>
  );
}
